#ifndef GUARD_LIBOMVTK_NETWORK_LOGIN_H_INCLUDED
#define GUARD_LIBOMVTK_NETWORK_LOGIN_H_INCLUDED

namespace omvtk
{
	struct Login
	{
		Login();
	};
}

#endif //GUARD_LIBOMVTK_NETWORK_LOGIN_H_INCLUDED

